version: "3.8"

services:

  # =========================
  # (POSTGRESQL)
  # =========================
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: appdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app_network


  # =========================
  # PASSBOLT DATABASE (MYSQL COMPATIBLE)
  # =========================
  passbolt_db:
    image: mariadb:10.11
    container_name: passbolt_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: passboltpass

    volumes:
      - passbolt_data:/var/lib/mysql

    networks:
      - app_network


  # =========================
  # PASSBOLT APP
  # =========================
  passbolt:
    image: passbolt/passbolt:latest-ce
    container_name: passbolt_app
    restart: always

    depends_on:
      - passbolt_db

    ports:
      - "9797:80"

    environment:
      APP_FULL_BASE_URL: http://localhost:9797

      DATASOURCES_DEFAULT_HOST: passbolt_db
      DATASOURCES_DEFAULT_USERNAME: passbolt
      DATASOURCES_DEFAULT_PASSWORD: passboltpass
      DATASOURCES_DEFAULT_DATABASE: passbolt
      DATASOURCES_DEFAULT_DRIVER: Cake\Database\Driver\Mysql

    networks:
      - app_network


# =========================
# VOLUMES
# =========================
volumes:
  postgres_data:
  passbolt_data:


# =========================
# NETWORK
# =========================
networks:
  app_network: